export type Province = {
  key: string;
  label: string;
};

export const provinces: Province[] = [
  { key: "", label: "Tất cả" },
  { key: "HANOI", label: "Hà Nội" },
  { key: "HOCHIMINH", label: "TP. Hồ Chí Minh" },
  { key: "DANANG", label: "Đà Nẵng" },
  { key: "HAIPHONG", label: "Hải Phòng" },
  { key: "CANTHO", label: "Cần Thơ" },
  { key: "HAGIANG", label: "Hà Giang" },
  { key: "CAOBANG", label: "Cao Bằng" },
  { key: "BACGIANG", label: "Bắc Giang" },
  { key: "BACCAN", label: "Bắc Kạn" },
  { key: "TUYENQUANG", label: "Tuyên Quang" },
  { key: "LAOCAI", label: "Lào Cai" },
  { key: "DIENBIEN", label: "Điện Biên" },
  { key: "LAICHAU", label: "Lai Châu" },
  { key: "SONLA", label: "Sơn La" },
  { key: "YENBAI", label: "Yên Bái" },
  { key: "HOABINH", label: "Hòa Bình" },
  { key: "THAINGUYEN", label: "Thái Nguyên" },
  { key: "LANGSON", label: "Lạng Sơn" },
  { key: "QUANGNINH", label: "Quảng Ninh" },
  { key: "PHUTHO", label: "Phú Thọ" },
  { key: "VINHPHUC", label: "Vĩnh Phúc" },
  { key: "BACNINH", label: "Bắc Ninh" },
  { key: "HAIDUONG", label: "Hải Dương" },
  { key: "HUNGYEN", label: "Hưng Yên" },
  { key: "THAIBINH", label: "Thái Bình" },
  { key: "HANAM", label: "Hà Nam" },
  { key: "NAMDINH", label: "Nam Định" },
  { key: "NINHBINH", label: "Ninh Bình" },
  { key: "THANHHOA", label: "Thanh Hóa" },
  { key: "NGHEAN", label: "Nghệ An" },
  { key: "HATINH", label: "Hà Tĩnh" },
  { key: "QUANGBINH", label: "Quảng Bình" },
  { key: "QUANGTRI", label: "Quảng Trị" },
  { key: "THUATHIENHUE", label: "Thừa Thiên Huế" },
  { key: "QUANGNAM", label: "Quảng Nam" },
  { key: "QUANGNGAI", label: "Quảng Ngãi" },
  { key: "BINHDINH", label: "Bình Định" },
  { key: "PHUYEN", label: "Phú Yên" },
  { key: "KHANHHOA", label: "Khánh Hòa" },
  { key: "NINHTHUAN", label: "Ninh Thuận" },
  { key: "BINHTHUAN", label: "Bình Thuận" },
  { key: "KONTUM", label: "Kon Tum" },
  { key: "GIALAI", label: "Gia Lai" },
  { key: "DAKLAK", label: "Đắk Lắk" },
  { key: "DAKNONG", label: "Đắk Nông" },
  { key: "LAMDONG", label: "Lâm Đồng" },
  { key: "BINHPHUOC", label: "Bình Phước" },
  { key: "TAYNINH", label: "Tây Ninh" },
  { key: "BINHDUONG", label: "Bình Dương" },
  { key: "DONGNAI", label: "Đồng Nai" },
  { key: "BARIAVUNGTAU", label: "Bà Rịa - Vũng Tàu" },
  { key: "LONGAN", label: "Long An" },
  { key: "TIENGIANG", label: "Tiền Giang" },
  { key: "BENTRE", label: "Bến Tre" },
  { key: "TRAVINH", label: "Trà Vinh" },
  { key: "VINHLONG", label: "Vĩnh Long" },
  { key: "DONGTHAP", label: "Đồng Tháp" },
  { key: "ANGIANG", label: "An Giang" },
  { key: "KIENGIANG", label: "Kiên Giang" },
  { key: "HAUGIANG", label: "Hậu Giang" },
  { key: "SOCTRANG", label: "Sóc Trăng" },
  { key: "BACLIU", label: "Bạc Liêu" },
  { key: "CAMAU", label: "Cà Mau" },
];
