export type Province = {
  key: string;
  label: string;
};

export const provinces: Province[] = [
  { key: "", label: "Tất cả" },
  { key: "1", label: "Hà Nội" },
  { key: "2", label: "TP Hồ Chí Minh" },
  { key: "3", label: "An Giang" },
  { key: "4", label: "Bà Rịa-Vũng Tàu" },
  { key: "5", label: "Bắc Giang" },
  { key: "6", label: "Bắc Kạn" },
  { key: "7", label: "Bạc Liêu" },
  { key: "8", label: "Bắc Ninh" },
  { key: "9", label: "Bến Tre" },
  { key: "10", label: "Bình Dương" },
  { key: "11", label: "Bình Định" },
  { key: "12", label: "Bình Phước" },
  { key: "13", label: "Bình Thuận" },
  { key: "14", label: "Cà Mau" },
  { key: "15", label: "Cao Bằng" },
  { key: "16", label: "Cần Thơ" },
  { key: "17", label: "Đà Nẵng" },
  { key: "18", label: "Đắk Lắk" },
  { key: "19", label: "Đắk Nông" },
  { key: "20", label: "Điện Biên" },
  { key: "21", label: "Đồng Nai" },
  { key: "22", label: "Đồng Tháp" },
  { key: "23", label: "Gia Lai" },
  { key: "24", label: "Hà Giang" },
  { key: "25", label: "Hà Nam" },
  { key: "26", label: "Hà Tĩnh" },
  { key: "27", label: "Hải Dương" },
  { key: "28", label: "Hải Phòng" },
  { key: "29", label: "Hậu Giang" },
  { key: "30", label: "Hòa Bình" },
  { key: "31", label: "Hưng Yên" },
  { key: "32", label: "Khánh Hòa" },
  { key: "33", label: "Kiên Giang" },
  { key: "34", label: "Kon Tum" },
  { key: "35", label: "Lai Châu" },
  { key: "36", label: "Lâm Đồng" },
  { key: "37", label: "Lạng Sơn" },
  { key: "38", label: "Lào Cai" },
  { key: "39", label: "Long An" },
  { key: "40", label: "Nam Định" },
  { key: "41", label: "Nghệ An" },
  { key: "42", label: "Ninh Bình" },
  { key: "43", label: "Ninh Thuận" },
  { key: "44", label: "Phú Thọ" },
  { key: "45", label: "Phú Yên" },
  { key: "46", label: "Quảng Bình" },
  { key: "47", label: "Quảng Nam" },
  { key: "48", label: "Quảng Ngãi" },
  { key: "49", label: "Quảng Ninh" },
  { key: "50", label: "Quảng Trị" },
  { key: "51", label: "Sóc Trăng" },
  { key: "52", label: "Sơn La" },
  { key: "53", label: "Tây Ninh" },
  { key: "54", label: "Thái Bình" },
  { key: "55", label: "Thái Nguyên" },
  { key: "56", label: "Thanh Hóa" },
  { key: "57", label: "Thừa Thiên Huế" },
  { key: "58", label: "Tiền Giang" },
  { key: "59", label: "Trà Vinh" },
  { key: "60", label: "Tuyên Quang" },
  { key: "61", label: "Vĩnh Long" },
  { key: "62", label: "Vĩnh Phúc" },
  { key: "63", label: "Yên Bái" }
];
