
spring:
  datasource:
    url: jdbc:mysql://103.188.83.147:3306/sale_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC-7
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gradingbkost
    password: zR1T^xk!7+NVW+Q
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    from: vannguyen.ithust@gmail.com
    host: smtp.gmail.com
    port: 587
    username: vannguyen.ithust@gmail.com
    password: wzws eaks wasr dtlj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      wrap-root-value: true
    deserialization:
      unwrap-root-value: true

token:
  jwt:
    secret-key: a5RsQm2rhY3GMgD51qK3E+aYPoe5IsnfYD0QFydCoQ0=
    expiration: 2592000
    expiration-refresh-token: 5184000

omni:
  store:
    suffix-domain: .mysale.net